---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: demo-sa
 namespace: sa-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: list-pods
rules:
  - apiGroups:
    - ''
    resources:
    - 'serviceaccounts'
    - 'sa'
    verbs:
    - 'list'
    - 'get'
    - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: list-pods_demo-sa
roleRef:
 kind: ClusterRole
 name: list-pods
 apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: demo-sa
    namespace: sa-manager
---
apiVersion: v1
kind: Pod
metadata:
 name: pod-demo-sa
 namespace: sa-manager
spec:
 serviceAccountName: demo-sa
 containers:
  - name: alpine
    image: golang:1.17.6-alpine
    command:
      - "sleep"
      - "3600"
---