---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  sa-manager
  namespace: sa-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["serviceaccounts","secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding 
metadata:
  name: tenant-binding-admin
  namespace: sa-manager
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: pod-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-manager
  namespace: sa-manager
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-manager
  namespace: sa-manager
spec:
  selector:
    matchLabels:
      app: sa-manager
  template:
    metadata:
      labels:
        app: sa-manager
    spec:
      serviceAccountName: sa-manager
      containers:
      - name: sa-manager
        image: "k8s.io/sa-manager:0.1-alpha16"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        env:
          - name: VERBOSITY
            value: "info"
          - name: GITLAB_BASEURL
            value: "gitlab.com"
          - name: GITLAB_TOKEN
            value: ""
          - name: RUN_IN_KATE
            value: "true"
