apiVersion: v1
kind: ServiceAccount
metadata:
  name:  seitosan
  labels:
    sa-manager/enabled: "true"
  annotations:
    sa-manager.k8s.io: "gitlab"
    #github.sa-manager.k8s.io/owner: "NoSpof"
    #github.sa-manager.k8s.io/repository: "sa-manager"
    #github.sa-manager.k8s.io/scope: "repo"
    #github.sa-manager.k8s.io/variable: "AKS_SEITOSAN"
    gitlab.sa-manager.k8s.io/id: "31418522"
    gitlab.sa-manager.k8s.io/scope: "projects"
    gitlab.sa-manager.k8s.io/variable: "AKS_DEV_KUBECONFIG"


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-binding-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
- kind: ServiceAccount
  name: seitosan
---